version: '3.8'
services:
  db:
    image: postgres:latest
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_DB: ktormpoc
      POSTGRES_USER: ktormpoc
      POSTGRES_PASSWORD: ktormpoc
    networks:
      - default